### ISSUE TITLE
docker-compose方式安装运行报错

### ISSUE THREAD

**Issue by Nodewebzsz** [tech-fever/nezha_telegram_bot#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/opt/nezha_telegram_bot/utils/handler.py", line 455, in search_command
    send_message = update.message.reply_text
AttributeError: 'NoneType' object has no attribute 'reply_text'

**Comment by Kosonlee** [comment]
docker run -d --name=nezhabot \
  --restart=always \
  -v /home/nezha/conf.ini:/opt/nezha_telegram_bot/conf.ini \
  -v /home/nezha/data/:/opt/nezha_telegram_bot/data/ \
  techfever/nezha_telegram_bot:latest

直接运行 前提你的ini文件目录保持一致
